### PR TITLE
Extend script for local builds. It will create a source deb archive, the...

### PR DESCRIPTION
**Pull request by rickysarraf**
...n build it with one of the builders (sbuild / pbuilder), then generate the Packages file, and then finally archive them all into a tarball

### CODE REVIEW

**Comment by sorenh** [comment]
Let's not add more functionality to sync-repo. See if you can put it all in debian/rules instead.

Also, using sbuild/pbuilder will make it take much longer to rebuild. This is part of a developer's workflow, so the clean-room nature of sbuild/pbuilder isn't necessary.

Put yourself in the developer's place. They're working on a new feature. They write a few lines of code, test it... write another few lines, test it. Fix a few lines, test it. Nothing slows down development like a long build cycle.

**Comment by rickysarraf** [comment]
Okay! I'll see what can be adapted in the makefile.

But regarding the developer workflow, if the whole autobuild repository is to be checked out and built without a builder like sbuild, there'll be quite a large number of build dependencies they'll need to install manually. And it'll still build all the packages.

**Comment by rickysarraf** [comment]
If the workflow is only for a single repository, like Ceph, where we wanted to speeden up the builds, it was done separately.

**Comment by sorenh** [comment]
The build-dependency list looks quite manageable to me:
               debhelper (>= 7),
               python-all (>= 2.6.6-3~),
               python-pbr (>= 0.6),
               python-setuptools,
               python-sphinx,
               python-prettytable,
               python-dev

I don't think that's an unreasonable set of packages to expect installed on a developer workstation.

Building a new (set of) package(s) should be much faster after the first build. You don't need to clean in between each run and compared to sbuild, you won't need to unpack a chroot, make sure it's up-to-date, etc., etc. dpkg-buildpackage -nc should be much faster than sbuild.

**Comment by rickysarraf** [comment]
Close this pull request because the (developer) build workflow will be very independent. Just the dpkg-buildpackage (with least dependency on external tools) should be able to build packages for the develpopers. Follow-up to come in a new pull request.

**Pull request closed without merging**
