### PR TITLE
Netifaces

### PR DESCRIPTION
**Pull request by bodepd**

### CODE REVIEW

**Comment by rickysarraf** [comment]
@sorenh Haven't read any comment back from you. You had some concerns about the additional list of build dependencies. Shall we merge the changes ?

**Comment by bodepd** [comment]
@rickysarraf I'm still not quite done here, I had a dependency failure related to python-tz that I was just looking at. I'll let you know when I can finally get the package builds working from scratch.

**Comment by bodepd** [comment]
This is the next things that needs to be resolved:

````
Traceback (most recent call last):
  File "/usr/bin/jorc", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (pytz 2012c (/usr/lib/python2.7/dist-packages), Requirement.parse('pytz>=2013.6'))
````

**Comment by rickysarraf** [comment]
On Tuesday 19 May 2015 04:21 AM, Dan Bode wrote:
>
> This is the next things that needs to be resolved:
>
> |Traceback (most recent call last): File "/usr/bin/jorc", line 5, in
> <module> from pkg_resources import load_entry_point File
> "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in
> <module> working_set = WorkingSet._build_master() File
> "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in
> _build_master return cls._build_from_requirements(__requires__) File
> "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in
> _build_from_requirements dists = ws.resolve(reqs, Environment()) File
> "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in
> resolve raise VersionConflict(dist,req) # XXX put more info here
> pkg_resources.VersionConflict: (pytz 2012c
> (/usr/lib/python2.7/dist-packages), Requirement.parse('pytz>=2013.6')) |
And pytz is maintianed in LP. I believe there was a recent announcement
that LP had started offering git services apart from bzr.

https://code.launchpad.net/pytz

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by bodepd** [comment]
I can walk through and finish this process, but my intention was to verify whether or not the tempest packages worked. There was no way to test it, so I built a testing workflow, and I have found that there were two mistakes related to package version inconsistencies. So, I'm pretty happy to just say at this point that the packages for tempest and the packages related to these patches to not work and move on.

**Comment by bodepd** [comment]
I was told that the packages were finished, but they are clearly not

**Comment by bodepd** [comment]
reopened as #16

**Pull request closed without merging**
